aname: aurelianosilva1426@gmail.co
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: aurelianosilva1426@gmail.co
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
